name: HIGNN Tests

on:
  push:
    branches: [ main ]  # Run on push to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Make Docker available
      uses: docker/setup-buildx-action@v3
    
    - name: Pull required images
      run: |
        docker pull panlabuwmadison/hignn:cpu

    - name: Compile HIGNN
      run: |
        docker run --privileged --rm \
        -v $PWD:/workspace \
        -w /workspace \
        --env BUILDKIT_INLINE_CACHE=1 \
        panlabuwmadison/hignn:cpu \
        python3 python/init.py --rebuild

    - name: Run tests
      run: |
        docker run --privileged --rm \
        -v $PWD:/workspace \
        -w /workspace \
        panlabuwmadison/hignn:cpu \
        sh -c "apt-get update && apt-get install libxrender1 && pytest -s test/test_engine.py"